package test.dao;

import java.util.List;
import test.model.CheckConstraints;

public interface CheckConstraintsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECK_CONSTRAINTS
     *
     * @mbg.generated
     */
    int insert(CheckConstraints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECK_CONSTRAINTS
     *
     * @mbg.generated
     */
    List<CheckConstraints> selectAll();
}