package test.dao;

import java.util.List;
import test.model.KeyringKeys;

public interface KeyringKeysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyring_keys
     *
     * @mbg.generated
     */
    int insert(KeyringKeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyring_keys
     *
     * @mbg.generated
     */
    List<KeyringKeys> selectAll();
}