package test.dao;

import java.util.List;
import test.model.StUnitsOfMeasure;

public interface StUnitsOfMeasureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST_UNITS_OF_MEASURE
     *
     * @mbg.generated
     */
    int insert(StUnitsOfMeasure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ST_UNITS_OF_MEASURE
     *
     * @mbg.generated
     */
    List<StUnitsOfMeasure> selectAll();
}