spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123456
    
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: tk.mybatis.springboot.model