package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table CHECK_CONSTRAINTS
 */
public class CheckConstraints {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_CONSTRAINTS.CONSTRAINT_CATALOG
     *
     * @mbg.generated
     */
    private String constraintCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_CONSTRAINTS.CONSTRAINT_SCHEMA
     *
     * @mbg.generated
     */
    private String constraintSchema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_CONSTRAINTS.CONSTRAINT_NAME
     *
     * @mbg.generated
     */
    private String constraintName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_CONSTRAINTS.CHECK_CLAUSE
     *
     * @mbg.generated
     */
    private String checkClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_CONSTRAINTS.CONSTRAINT_CATALOG
     *
     * @return the value of CHECK_CONSTRAINTS.CONSTRAINT_CATALOG
     *
     * @mbg.generated
     */
    public String getConstraintCatalog() {
        return constraintCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_CONSTRAINTS.CONSTRAINT_CATALOG
     *
     * @param constraintCatalog the value for CHECK_CONSTRAINTS.CONSTRAINT_CATALOG
     *
     * @mbg.generated
     */
    public void setConstraintCatalog(String constraintCatalog) {
        this.constraintCatalog = constraintCatalog == null ? null : constraintCatalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_CONSTRAINTS.CONSTRAINT_SCHEMA
     *
     * @return the value of CHECK_CONSTRAINTS.CONSTRAINT_SCHEMA
     *
     * @mbg.generated
     */
    public String getConstraintSchema() {
        return constraintSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_CONSTRAINTS.CONSTRAINT_SCHEMA
     *
     * @param constraintSchema the value for CHECK_CONSTRAINTS.CONSTRAINT_SCHEMA
     *
     * @mbg.generated
     */
    public void setConstraintSchema(String constraintSchema) {
        this.constraintSchema = constraintSchema == null ? null : constraintSchema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_CONSTRAINTS.CONSTRAINT_NAME
     *
     * @return the value of CHECK_CONSTRAINTS.CONSTRAINT_NAME
     *
     * @mbg.generated
     */
    public String getConstraintName() {
        return constraintName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_CONSTRAINTS.CONSTRAINT_NAME
     *
     * @param constraintName the value for CHECK_CONSTRAINTS.CONSTRAINT_NAME
     *
     * @mbg.generated
     */
    public void setConstraintName(String constraintName) {
        this.constraintName = constraintName == null ? null : constraintName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_CONSTRAINTS.CHECK_CLAUSE
     *
     * @return the value of CHECK_CONSTRAINTS.CHECK_CLAUSE
     *
     * @mbg.generated
     */
    public String getCheckClause() {
        return checkClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_CONSTRAINTS.CHECK_CLAUSE
     *
     * @param checkClause the value for CHECK_CONSTRAINTS.CHECK_CLAUSE
     *
     * @mbg.generated
     */
    public void setCheckClause(String checkClause) {
        this.checkClause = checkClause == null ? null : checkClause.trim();
    }
}