package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table replication_applier_configuration
 */
public class ReplicationApplierConfiguration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replication_applier_configuration.CHANNEL_NAME
     *
     * @mbg.generated
     */
    private String channelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replication_applier_configuration.DESIRED_DELAY
     *
     * @mbg.generated
     */
    private Integer desiredDelay;

    /**
     * Database Column Remarks:
     *   User name for the security context of the applier.
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replication_applier_configuration.PRIVILEGE_CHECKS_USER
     *
     * @mbg.generated
     */
    private String privilegeChecksUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replication_applier_configuration.CHANNEL_NAME
     *
     * @return the value of replication_applier_configuration.CHANNEL_NAME
     *
     * @mbg.generated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replication_applier_configuration.CHANNEL_NAME
     *
     * @param channelName the value for replication_applier_configuration.CHANNEL_NAME
     *
     * @mbg.generated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replication_applier_configuration.DESIRED_DELAY
     *
     * @return the value of replication_applier_configuration.DESIRED_DELAY
     *
     * @mbg.generated
     */
    public Integer getDesiredDelay() {
        return desiredDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replication_applier_configuration.DESIRED_DELAY
     *
     * @param desiredDelay the value for replication_applier_configuration.DESIRED_DELAY
     *
     * @mbg.generated
     */
    public void setDesiredDelay(Integer desiredDelay) {
        this.desiredDelay = desiredDelay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replication_applier_configuration.PRIVILEGE_CHECKS_USER
     *
     * @return the value of replication_applier_configuration.PRIVILEGE_CHECKS_USER
     *
     * @mbg.generated
     */
    public String getPrivilegeChecksUser() {
        return privilegeChecksUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replication_applier_configuration.PRIVILEGE_CHECKS_USER
     *
     * @param privilegeChecksUser the value for replication_applier_configuration.PRIVILEGE_CHECKS_USER
     *
     * @mbg.generated
     */
    public void setPrivilegeChecksUser(String privilegeChecksUser) {
        this.privilegeChecksUser = privilegeChecksUser == null ? null : privilegeChecksUser.trim();
    }
}