package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ST_UNITS_OF_MEASURE
 */
public class StUnitsOfMeasure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_UNITS_OF_MEASURE.UNIT_NAME
     *
     * @mbg.generated
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_UNITS_OF_MEASURE.UNIT_TYPE
     *
     * @mbg.generated
     */
    private String unitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_UNITS_OF_MEASURE.CONVERSION_FACTOR
     *
     * @mbg.generated
     */
    private Double conversionFactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ST_UNITS_OF_MEASURE.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_UNITS_OF_MEASURE.UNIT_NAME
     *
     * @return the value of ST_UNITS_OF_MEASURE.UNIT_NAME
     *
     * @mbg.generated
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_UNITS_OF_MEASURE.UNIT_NAME
     *
     * @param unitName the value for ST_UNITS_OF_MEASURE.UNIT_NAME
     *
     * @mbg.generated
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_UNITS_OF_MEASURE.UNIT_TYPE
     *
     * @return the value of ST_UNITS_OF_MEASURE.UNIT_TYPE
     *
     * @mbg.generated
     */
    public String getUnitType() {
        return unitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_UNITS_OF_MEASURE.UNIT_TYPE
     *
     * @param unitType the value for ST_UNITS_OF_MEASURE.UNIT_TYPE
     *
     * @mbg.generated
     */
    public void setUnitType(String unitType) {
        this.unitType = unitType == null ? null : unitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_UNITS_OF_MEASURE.CONVERSION_FACTOR
     *
     * @return the value of ST_UNITS_OF_MEASURE.CONVERSION_FACTOR
     *
     * @mbg.generated
     */
    public Double getConversionFactor() {
        return conversionFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_UNITS_OF_MEASURE.CONVERSION_FACTOR
     *
     * @param conversionFactor the value for ST_UNITS_OF_MEASURE.CONVERSION_FACTOR
     *
     * @mbg.generated
     */
    public void setConversionFactor(Double conversionFactor) {
        this.conversionFactor = conversionFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ST_UNITS_OF_MEASURE.DESCRIPTION
     *
     * @return the value of ST_UNITS_OF_MEASURE.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ST_UNITS_OF_MEASURE.DESCRIPTION
     *
     * @param description the value for ST_UNITS_OF_MEASURE.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}